### ISSUE TITLE
Bypass CORS issue

### ISSUE THREAD

**Issue by cmacdonnacha** [Atmosphere/bower-atmosphere#5]
Hi,

We are connecting to atmosphere which is on a separate domain. We'd like to be able to develop locally while connecting to atmosphere and I was wondering if there was a workaround to allow CORS?

Error:
XMLHttpRequest cannot load http://localhost:9080/XXXXXXXXXXX//broadcast?X-Atmosphere-tracking-id=…ng&X-Atmosphere-TrackMessageSize=true&X-atmo-protocol=true&_=1428573169075. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access. The response had HTTP status code 404.

Thanks,
Cathal.

**Comment by jfarcand** [comment]
Please use the mailing list https://groups.google.com/group/atmosphere-framework?pli=1

for question. Make sure you specify the version used and make sure the CORSInterceptor is installed.
