### ISSUE TITLE
Can we make 2.2.11 available?

### ISSUE THREAD

**Issue by bsbodden** [Atmosphere/bower-atmosphere#6]
Thanks!

**Comment by prismsoundzero** [comment]
I agree, that would be nice!

In the meantime you can use atmosphere-javascript repository in your bower.json file:

    "dependencies": {
        "atmosphere": "Atmosphere/atmosphere-javascript#javascript-project-2.2.11"
    }
    "overrides": {
        "atmosphere": {
            "main": [
                "modules/javascript/src/main/webapp/javascript/atmosphere.js"
            ]
        }
    }

**Comment by elakito** [comment]
this ticket was supposed to have been closed earlier.
we have had a couple of releases and the latest one 2.3.2 just came out.
